version: '3.8'

services:
  # PostgreSQL 데이터베이스
  postgres:
    image: postgres:15-alpine
    container_name: moyak-postgres
    environment:
      POSTGRES_DB: moyak_db
      POSTGRES_USER: moyak_user
      POSTGRES_PASSWORD: moyak_secure_password_2024
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U moyak_user -d moyak_db"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - moyak-network

  # MOYAK 애플리케이션
  moyak-app:
    build:
      context: .
      args:
        NODE_ENV: production
        REACT_APP_API_URL: http://your-service-ip:5434
    image: moyak-app:latest
    container_name: moyak-app
    environment:
      # 서버 설정
      NODE_ENV: production
      PORT: 5000
      
      # 데이터베이스 설정
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: moyak_db
      DB_USER: moyak_user
      DB_PASSWORD: moyak_secure_password_2024
      
      # JWT 설정
      JWT_SECRET: moyak_jwt_secret_key_2024_production
      JWT_EXPIRES_IN: 7d
      
      # 이메일 설정 (실제 값으로 변경 필요)
      EMAIL_HOST: smtp.gmail.com
      EMAIL_PORT: 587
      EMAIL_USER: your_email@gmail.com
      EMAIL_PASS: your_app_password
      
      # 프론트엔드 URL
      CLIENT_URL: http://your-service-ip:5434
    ports:
      - "5434:5000"  # 외부 포트 5434, 내부 포트 5000
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5000/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - moyak-network
    volumes:
      # 로그 볼륨 (선택사항)
      - moyak_logs:/app/logs

volumes:
  postgres_data:
    driver: local
  moyak_logs:
    driver: local

networks:
  moyak-network:
    driver: bridge 